site_name: Aplicações de Redes de Computadores
site_author: Emilly Jenniffer

theme:
  name: material
  language: pt

repo_name: ifrnlab/apr-2023-2
repo_url: https://EmillyJenni.github.io/apr-2023-2/
edit_uri: edit/main/docs

nav:
- index.md
- pedra.md
- papel.md
- tesoura.md
- ensaios:
  - ensaios/mermaid.md

plugins:
- mermaid2